name: CI/CD Pipeline for UserManagementBackend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup SSH Key
      - name: Setup SSH Key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}  # Your private SSH key stored in GitHub Secrets
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem

      # Step 3: Connect to EC2 and Pull Latest Code
      - name: Pull Latest Code from Git
        env:
          EC2_USER: ${{ secrets.EC2_USER }}  # EC2 username (e.g., ubuntu)
          EC2_IP: ${{ secrets.EC2_IP }}      # Your EC2 public IP
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP '
          set -e  # Exit immediately if a command exits with a non-zero status
            cd ~/UserEcommerceClean/cmd
            git pull origin main
          '

      # Step 4: Build Go Application
      - name: Build Go Application
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP '
          set -e  # Exit immediately if a command exits with a non-zero status
            cd ~/UserEcommerceClean/cmd
            go mod tidy
            cd ..
            go test ./internal/controllers -v  # Adjust according to your test path
            cd cmd
            go build -o main.exe main.go
          '

      # Step 5: Restart Application Service
      - name: Restart Application Service
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no $EC2_USER@$EC2_IP '
          set -e  # Exit immediately if a command exits with a non-zero status
            sudo systemctl restart userecommerce.service  # Adjust service name as necessary
          '

      # Step 6: Cleanup SSH Key
      - name: Cleanup
        run: |
          rm -f key.pem
